import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface Inspection {
  id: string;
  client_name: string;
  client_email: string | null;
  client_phone: string | null;
  rug_number: string;
  rug_type: string;
  length: number | null;
  width: number | null;
  notes: string | null;
  photo_urls: string[] | null;
  analysis_report: string | null;
  created_at: string;
}

export const generatePDF = async (inspection: Inspection): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Rug Inspection Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Report Date: ${format(new Date(inspection.created_at), 'MMMM d, yyyy')}`,
    pageWidth / 2,
    yPos,
    { align: 'center' }
  );
  yPos += 20;

  // Client Information Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Client Information', margin, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const clientInfo = [
    ['Name', inspection.client_name],
    ['Email', inspection.client_email || 'N/A'],
    ['Phone', inspection.client_phone || 'N/A'],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: clientInfo,
    theme: 'plain',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40 },
      1: { cellWidth: 'auto' },
    },
    margin: { left: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Rug Details Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Rug Details', margin, yPos);
  yPos += 8;

  const rugDetails = [
    ['Rug Number', inspection.rug_number],
    ['Type', inspection.rug_type],
    [
      'Dimensions',
      inspection.length && inspection.width
        ? `${inspection.length}' × ${inspection.width}'`
        : 'N/A',
    ],
    ['Notes', inspection.notes || 'N/A'],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: rugDetails,
    theme: 'plain',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40 },
      1: { cellWidth: 'auto' },
    },
    margin: { left: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // AI Analysis Section
  if (inspection.analysis_report) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('AI Analysis & Recommendations', margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    // Split the report into lines that fit the page width
    const maxWidth = pageWidth - margin * 2;
    const lines = doc.splitTextToSize(inspection.analysis_report, maxWidth);

    // Check if we need a new page
    const lineHeight = 5;
    const pageHeight = doc.internal.pageSize.getHeight();

    for (let i = 0; i < lines.length; i++) {
      if (yPos + lineHeight > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
      doc.text(lines[i], margin, yPos);
      yPos += lineHeight;
    }
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by RugInspect',
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  // Save the PDF
  const fileName = `rug-inspection-${inspection.rug_number}-${format(
    new Date(inspection.created_at),
    'yyyy-MM-dd'
  )}.pdf`;
  doc.save(fileName);
};
